### ISSUE TITLE
у платёжного модуля нет возможности продолжить оплату

### ISSUE THREAD

**Issue by morikoff** [modulbank-pay/modulbank-prestashop#2]
пожалуйста, рассмотрите возможность доделать модуль до совершенства.

как сейчас: покупатель кладёт товар в корзину выбирает оплату модульбанк, и в момент перехода на страницу банка для оплаты в магазине создаётся заказ со статусом "ожидает оплаты" (с указанием платёжного модуля модульбанка). И если клиент прерывает свои действия и уходит со страницы оплаты, то он больше не сможет на неё вернуться и продолжить оплату, а в магазине завис ещё один заказ и навечно "ожидает оплату". 

как надо: если бы клиент открыл свой личный кабинет на сайте, и нашёл свой последний "не оплаченный" заказ и там была бы кнопка/ссылка "Продолжить оплату", он мог бы перейти повторно на страницу банка и завершить оплату, и его заказ в магазине получил бы статус "Оплачен". Вот так всё замечательно.

**Comment by VampiRUS** [comment]
На странице заказа добавлена кнопка
