### ISSUE TITLE
В чек не передаётся название товара с комбинацией

### ISSUE THREAD

**Issue by morikoff** [modulbank-pay/modulbank-prestashop#3]
В магазине имеются товары с комбинациями и названия таких товаров неправильно попадают в кассовый чек. Например "Выключатель", имеет комбинации "1 кнопка", "2 кнопки", "4 кнопки", "6 кнопок". Покупатель выбрал "Выключатель, 2 кнопки", но в кассовый чек попадает название родительского товара "Выключатель", т.е. без комбинации "2 кнопки". Однако, в магазине заказ формируется с комбинацией и выглядит как "Выключатель, 2 кнопки". К тому же, родительский товар не имеет артикула, а дочерний имеет. Но в чеке уже нет этой комбинации, нельзя по чеку понять, что куплено.

Ниже пример как это делал другой платёжны модуль, главное, что название было из комбинации товара.

![2022-08-12_224_11-58-36](https://user-images.githubusercontent.com/13396266/184323047-ecb6f74d-822a-4401-8a1a-1f31fbc1f6b9.png)

**Comment by morikoff** [comment]
Извините, но рано закрылся Issue. Про артикул забыто. 
И важно учесть, чтобы при выводе комбинации был артикул именно комбинации, а не артикул родительского. Родительский только в случае, если нет комбинации. 
Вот, что сейчас получили на исправленном модуле:
![Snimok_ekrana_ot_2023-12-28_19-48-40](https://github.com/modulbank-pay/modulbank-prestashop/assets/13396266/ed06e404-a334-4997-a531-dd8c7792e95a)

**Comment by VampiRUS** [comment]
Когда вы говорите артикул, то какое поле подразумеваете?
![image](https://github.com/modulbank-pay/modulbank-prestashop/assets/433120/ff8c3bf6-5b75-4491-b08c-494af0189ba8)

**Comment by morikoff** [comment]
На вашей картинке это штрих коды, чаще используется EAN13, но это не надо.

Артикул продукта без комбинаций - в главной карточке товара.
Вот без комбинации:

![2023-12-29_074829_(1416x575)](https://github.com/modulbank-pay/modulbank-prestashop/assets/13396266/0328779a-e471-41af-888d-e49f9bf2f690)

Артикул у товара с комбинациями находится внутри каждой комбинации.
Вот в комбинации (из карточки в комбинацию):
 
![2023-12-29_075002_(1412x666)](https://github.com/modulbank-pay/modulbank-prestashop/assets/13396266/44691525-0037-4f4c-aebe-a8328ba30930)

![2023-12-29_075047_(1344x453)](https://github.com/modulbank-pay/modulbank-prestashop/assets/13396266/451d8cfd-abbd-43d2-924b-111f5d11fea0)

**Comment by VampiRUS** [comment]
Добавлено

**Comment by morikoff** [comment]
> Добавлено

Замечательно, и хотелось бы как на картинке с квадратными скобками, чтобы не сливалось:
https://github.com/modulbank-pay/modulbank-prestashop/issues/3#issue-1336953050

сейчас так:
![2024-01-15_(1600x900)_181625](https://github.com/modulbank-pay/modulbank-prestashop/assets/13396266/fcd42a0d-9482-4bac-9d15-ea7dc8249b14)
желательно вот так:
![2024-01-15_(820x925)_181827](https://github.com/modulbank-pay/modulbank-prestashop/assets/13396266/96d19877-02ee-422e-bd16-77816009be01)

И видимо строка названия товара где-то обрезается по длине.

**Comment by VampiRUS** [comment]
Добавлено

**Comment by morikoff** [comment]
> Добавлено

Изумительно. Спасибо
